trigger:
- master

pool: laptop

jobs:
  - job: Build
    displayName: '(Build) Install node and build'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'
      
  - job: SCA
    displayName: '(SCA) OWASP Dependancy Check'
  
    variables:
      - group: Keys

    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
      displayName: 'Install Java (OpenJDK 11)'

    - script: |
        echo "##vso[task.setvariable variable=JAVA_HOME]$(dirname $(dirname $(readlink -f $(which java))))"
        export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      displayName: 'Set JAVA_HOME'
      
    - script: |
        curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
        unzip dependency-check.zip -d owasp-dependency-check
      displayName: 'Download OWASP Dependency-Check'

    - script: |
        export NVD_API_KEY=$(NVD_API_KEY)
        ./owasp-dependency-check/dependency-check/bin/dependency-check.sh --project "JuiceShop" --scan . --out ./dependency-check-report --nvdApiKey $(NVD_API_KEY)
      displayName: 'Run OWASP Dependency-Check'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'dependency-check-report'
        artifactName: 'DependencyCheckReport'
      displayName: 'Publish OWASP Dependency-Check Report'

  - job: Run
    displayName: '(Run) Run app'

    steps:
    - script: |
        npm run
      displayName: 'npm run'